# Generated by Django 2.0 on 2018-10-12 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='filetype',
            field=models.CharField(max_length=20),
        ),
    ]
